[tool.poetry]
name = "githubtest"
version = "0.1.0"
description = ""
authors = ["traditionallimb <dom@kalowe.me.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
